(function () {
  // Preconnects
  const preconnect1 = document.createElement("link");
  preconnect1.rel = "preconnect";
  preconnect1.href = "https://fonts.googleapis.com";

  const preconnect2 = document.createElement("link");
  preconnect2.rel = "preconnect";
  preconnect2.href = "https://fonts.gstatic.com";
  preconnect2.crossOrigin = "true";

  // Preload Google Font
  const preload = document.createElement("link");
  preload.rel = "preload";
  preload.as = "style";
  preload.href =
    "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap";

  // Load Google Font stylesheet non-blocking
  const stylesheet = document.createElement("link");
  stylesheet.rel = "stylesheet";
  stylesheet.href =
    "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap";
  stylesheet.media = "print";
  stylesheet.onload = function () {
    this.media = "all";
  };

  // Site icons: only the Lucide icons we use (generated by
  // scripts/build-icons.mjs), not the ~450KB full bundle.
  const iconScript = document.createElement("script");
  iconScript.src = "/src/js/icons.js";

  // Append to head
  document.head.appendChild(preconnect1);
  document.head.appendChild(preconnect2);
  document.head.appendChild(preload);
  document.head.appendChild(stylesheet);
  if (document.querySelector("i[data-lucide]")) {
    document.head.appendChild(iconScript);
  }
})();
