// Builds src/js/icons.js: a drop-in for the Lucide UMD bundle containing only
// the icons the site actually references via data-lucide="name".
// Run: npm run icons (also runs as part of npm run build).
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { icons } from "lucide";

const ROOT = new URL("..", import.meta.url).pathname;
// webDemo builds icon names at runtime, so it keeps the full Lucide bundle.
const SKIP = new Set(["node_modules", "dist", ".git", "webDemo"]);

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(path);
    else if (/\.(html|js)$/.test(entry.name)) yield path;
  }
}

const pascal = (name) =>
  name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

const names = new Set();
for (const file of walk(ROOT)) {
  for (const [, value] of readFileSync(file, "utf8").matchAll(
    /data-lucide="([^"]*)"/g,
  )) {
    // Plain name, or a template expression like ${x ? 'bitcoin' : 'dollar-sign'}
    const found = /^[a-z0-9-]+$/.test(value)
      ? [value]
      : [...value.matchAll(/'([a-z0-9-]+)'/g)].map((m) => m[1]);
    found.forEach((name) => names.add(name));
  }
}

const used = {};
for (const name of [...names].sort()) {
  if (!icons[pascal(name)]) throw new Error(`Unknown Lucide icon "${name}"`);
  used[name] = icons[pascal(name)];
}

writeFileSync(
  join(ROOT, "src/js/icons.js"),
  `// GENERATED by scripts/build-icons.mjs - do not edit. Run \`npm run icons\`.
// Only the Lucide icons this site uses, with a lucide.createIcons() shim.
(function () {
  var ICONS = ${JSON.stringify(used)};
  var NS = "http://www.w3.org/2000/svg";
  var DEFAULTS = {
    xmlns: NS, width: "24", height: "24", viewBox: "0 0 24 24", fill: "none",
    stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round",
    "stroke-linejoin": "round",
  };

  function createIcons() {
    document.querySelectorAll("i[data-lucide]").forEach(function (el) {
      var name = el.getAttribute("data-lucide");
      var node = ICONS[name];
      if (!node) {
        console.warn('icons.js: "' + name + '" missing, run npm run icons');
        return;
      }
      var svg = document.createElementNS(NS, "svg");
      Object.keys(DEFAULTS).forEach(function (k) {
        svg.setAttribute(k, DEFAULTS[k]);
      });
      Array.prototype.forEach.call(el.attributes, function (a) {
        svg.setAttribute(a.name, a.value);
      });
      svg.setAttribute(
        "class",
        ("lucide lucide-" + name + " " + (el.getAttribute("class") || "")).trim(),
      );
      // Icons are decorative; buttons/links carry their own labels.
      if (!svg.hasAttribute("aria-hidden")) svg.setAttribute("aria-hidden", "true");
      svg.setAttribute("focusable", "false");
      node.forEach(function (child) {
        var c = document.createElementNS(NS, child[0]);
        Object.keys(child[1]).forEach(function (k) {
          c.setAttribute(k, child[1][k]);
        });
        svg.appendChild(c);
      });
      el.replaceWith(svg);
    });
  }

  window.lucide = { createIcons: createIcons };
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", createIcons);
  } else {
    createIcons();
  }
})();
`,
);
console.log(`icons.js: ${names.size} icons`);
